### ISSUE TITLE
Formulas for specifying models presented on slides 33:35

### ISSUE THREAD

**Issue by konradsemsch** [mitchelloharawild/fasster_user2018#2]
Hi @mitchelloharawild!

Thanks again for an awesome forecasting package and presentation. I was hoping that perhaps you could share the underlying code to specify FASSTER models from slides 33:35 - I think having these tangible examples at hand would greatly help understand how to best specify such a model with complicated seasonalities etc. Would that be possible?

**Comment by mitchelloharawild** [comment]
These slides are directly from my thesis on the topic which is unpublished. The code for this is a few years old (pre-dating fable), and so it would take some time to update the code.

Some changes have been made to fasster since the talk, but comparable results follow. This code is certainly not an example of what I would do using fable today, rather a minimal conversion of the original code to work with the current versions of packages.

``` r
library(fasster)
#> Loading required package: fabletools
library(fpp3)
#> ── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── fpp3 0.1 ──
#> ✓ tibble      2.99.99.9014     ✓ tsibble     0.8.9.9000  
#> ✓ dplyr       0.8.5            ✓ tsibbledata 0.1.0.9000  
#> ✓ tidyr       1.0.2            ✓ feasts      0.1.2.9000  
#> ✓ lubridate   1.7.4            ✓ fable       0.1.2       
#> ✓ ggplot2     3.3.0.9000
#> ── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── fpp3_conflicts ──
#> x lubridate::date()       masks base::date()
#> x dplyr::filter()         masks stats::filter()
#> x tsibble::interval()     masks lubridate::interval()
#> x dplyr::lag()            masks stats::lag()
#> x tsibble::new_interval() masks lubridate::new_interval()
library(mgcv)
#> Loading required package: nlme
#> 
#> Attaching package: 'nlme'
#> The following object is masked from 'package:feasts':
#> 
#>     ACF
#> The following object is masked from 'package:dplyr':
#> 
#>     collapse
#> This is mgcv 1.8-31. For overview type 'help("mgcv-package")'.
library(prophet)
#> Loading required package: Rcpp
#> Loading required package: rlang
library(forecast)
#> Registered S3 method overwritten by 'quantmod':
#>   method            from
#>   as.zoo.data.frame zoo
#> 
#> Attaching package: 'forecast'
#> The following object is masked from 'package:nlme':
#> 
#>     getResponse
#> The following objects are masked from 'package:fabletools':
#> 
#>     GeomForecast, StatForecast
holidayfn <- function(years){
  holiday_aus(years) %>%
    bind_rows(tibble(holiday = "Grand Final Day", date = ymd(c("2016-09-30", "2017-09-29")))) %>%
    pull(date)
}
is_workday <- function(DateTime){
  ifelse(wday(DateTime) %in% c(1, 7) | date(DateTime) %in% holidayfn(unique(year(DateTime))), "!wday", "wday") %>%
    factor()
}
getTime <- function(model, series){
  eval(as.name(paste(series, "time", tolower(model), sep="_")))[[3]]
}

pedestrian <- rwalkr::melb_walk_fast(
  year = 2016:2017,
  sensor = "Southern Cross Station",
  na.rm = TRUE) %>%
  as_tsibble(index = Date_Time) %>% 
  filter(Date < ymd("2017-10-01"))

pedestrian_tsbl_train <- pedestrian %>%
  head(-24*7*2)
pedestrian_tsbl_test <- pedestrian %>%
  tail(24*7*2)

# FASSTER
pedestrian_time_fasster <- system.time({
  pedestrian_fit_fasster <- pedestrian_tsbl_train %>% model(fasster(Count ~ is_workday(Date_Time) %S% (poly(1) + fourier("day")), include = 1000))
  pedestrian_fc_fasster <- pedestrian_fit_fasster %>% forecast(new_data = pedestrian_tsbl_test)
})

# GAM
pedestrian_time_gam <- system.time({
  pedestrian_fit_gam <- gam(Count ~ workday + 
                              te(Time, wday,
                                 k = c(24, 7),
                                 bs = c("cr", "ps"),
                                 fx = TRUE),
                            data = pedestrian_tsbl_train %>% mutate(workday = is_workday(Date_Time), wday = wday(Date_Time)),
                            family = gaussian)
  pedestrian_fc_gam <- predict.gam(pedestrian_fit_gam, pedestrian_tsbl_test %>% mutate(workday = is_workday(Date_Time), wday = wday(Date_Time)))
})

# Prophet
pedestrian_time_prophet <- system.time({
  pedestrian_fit_prophet <- pedestrian_tsbl_train %>% 
    rename(ds = Date_Time, y = Count) %>%
    prophet(holidays = holiday_aus(2016:2017) %>% rename(ds = date))
  pedestrian_fc_prophet <- pedestrian_fit_prophet %>%
    predict(df = pedestrian_tsbl_test %>% rename(ds = Date_Time) %>% select(ds) %>% as.data.frame)
})
#> Disabling yearly seasonality. Run prophet with yearly.seasonality=TRUE to override this.
#> Warning: `data_frame()` is deprecated as of tibble 1.1.0.
#> Please use `tibble()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> Warning: `as_data_frame()` is deprecated as of tibble 2.0.0.
#> Please use `as_tibble()` instead.
#> The signature and semantics have changed, see `?as_tibble`.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.

# TBATS
pedestrian_time_tbats <- system.time({
  pedestrian_fit_tbats <- pedestrian_tsbl_train %>% 
    fill_gaps %>%
    pull(Count) %>%
    tail(24*7*6) %>%
    msts(seasonal.periods = c(24, 24*7)) %>%
    tbats(use.box.cox=TRUE)
  pedestrian_fc_tbats <- forecast(pedestrian_fit_tbats, h=NROW(pedestrian_tsbl_test))
})

# Combine
pedestrian_fc_all <- pedestrian_tsbl_test %>%
  select(Date_Time, Count) %>%
  rename(Actual = Count) %>%
  mutate(FASSTER = pedestrian_fc_fasster$Count,
         GAM = pedestrian_fc_gam,
         Prophet = pedestrian_fc_prophet$yhat,
         TBATS = pedestrian_fc_tbats$mean)

pedestrian_fc_all %>%
  as_tibble %>%
  gather(Model, Forecasts, -Date_Time, -Actual) %>%
  ggplot() +
  geom_line(aes(x=Date_Time, y=Forecasts, colour = Model)) + 
  geom_line(aes(x=Date_Time, y=Count), pedestrian_tsbl_train %>% tail(24*7*3)) +
  geom_line(aes(x=Date_Time, y=Count), pedestrian_tsbl_test, linetype="dashed") +
  guides(colour = guide_legend(NULL)) +
  xlab("Time (Interval: 1HOUR)") + 
  ylab("Pedestrians counted") + 
  theme(legend.position = "bottom")
#> Warning: attributes are not identical across measure variables;
#> they will be dropped
```

![](https://i.imgur.com/qKP2z0M.png)

``` r

pedestrian_fc_all %>%
  mutate_at(vars(FASSTER:TBATS), ~ . - Actual) %>%
  gather(Model, Error, -Date_Time, - Actual) %>%
  as_tibble() %>% 
  group_by(Model) %>%
  summarise(`Time (s)` = getTime(Model, "pedestrian"),
            RMSE = RMSE(Error),
            MAE = MAE(Error),
            MASE = MASE(Error, Actual, .period = 24)
  ) %>%
  knitr::kable(caption='Model performance on hourly pedestrian counts') %>%
  kableExtra::kable_styling(latex_options = "hold_position")
#> Warning: attributes are not identical across measure variables;
#> they will be dropped
#> Warning in kableExtra::kable_styling(., latex_options = "hold_position"): Please
#> specify format in kable. kableExtra can customize either HTML or LaTeX outputs.
#> See https://haozhu233.github.io/kableExtra/ for details.
```

<table>
<caption>Model performance on hourly pedestrian counts</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Time (s)</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">MASE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FASSTER</td>
<td style="text-align: right;">7.620</td>
<td style="text-align: right;">78.5722</td>
<td style="text-align: right;">47.79711</td>
<td style="text-align: right;">0.1626213</td>
</tr>
<tr class="even">
<td style="text-align: left;">GAM</td>
<td style="text-align: right;">1.454</td>
<td style="text-align: right;">278.3946</td>
<td style="text-align: right;">151.17392</td>
<td style="text-align: right;">0.5143428</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prophet</td>
<td style="text-align: right;">6.136</td>
<td style="text-align: right;">650.7286</td>
<td style="text-align: right;">488.82703</td>
<td style="text-align: right;">1.6631484</td>
</tr>
<tr class="even">
<td style="text-align: left;">TBATS</td>
<td style="text-align: right;">33.755</td>
<td style="text-align: right;">496.4910</td>
<td style="text-align: right;">322.71175</td>
<td style="text-align: right;">1.0979702</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-03-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by konradsemsch** [comment]
Thanks for sharing! Two questions on this one:

1) So in FASSTER you're switching not only on weekend/ working day but also holiday in a single call. I understand that you're also trying to model the behaviour of 'special' events by turning switching on it, but why are you doing it in a single call? Isn't it gonna mask the behaviour on that special event that might be different than on a weekend? I haven't actually tried yet if having multiple switches is possible.

Also, when specifying seasonal terms, e.g. weekly and yearly seasonality (if we have daily data), then would you rather specify them within each switch term separately, or also keep them outside of the switch? The same question applies for instance to poly(1) - to specify the level within the switch, as well as a general level outside the switch?

I think essentially my question comes down to: how much general information keep in the switch versus outside of the switch, and should that info overlap?

2) What is the `include = 1000` param exactly intended to do here? I noticed you're specifying the `trig` without mentioning the number of terms to create, so is this related?

**Comment by mitchelloharawild** [comment]
1. In the above example, weekends and holidays are being lumped into the same group. But fundamentally, yes: if the function returned a character/factor, then each unique value will be switched on. Looking at the data it seemed that holidays and weekends had a similar pattern, and so separating them didn't seem necessary. The model specification isn't really optimised here, and I'm sure a better model can be written (especially with the new  `%?%` conditional components).  

Choosing what to include in the switch depends on the data. For the pedestrian data, both the level and seasonality change in working and non-working days. In other examples, the level may not change and so it should be kept outside of the switching operator.

The states in and out of switching can overlap, but you should be careful that the overlap represents the structure in the data. For example you may have an overall annual seasonality, with a daily seasonality that switches on the type of day (weekday, weekend, holiday).

2. `include` is a bad argument and will likely be removed as it is inconsistent with the design of fable. It is for speeding up estimation by only modelling the most recent 1000 observations. The exclusion of `K` is also not recommended, and only works as a side-effect of `dlm::dlmModTrig()`. A lot has changed in ~ 3 years :smile:

**Comment by konradsemsch** [comment]
1. Cool - that makes sense! Could you elaborate on the `%?%` conditional component? Is it something that can be used already? I haven't seen it in the documentation.

2. Haha, understood :P

**Comment by mitchelloharawild** [comment]
It is pretty new and so not documented.
https://github.com/tidyverts/fasster/issues/26

Essentially it allows terms to be included according to a condition. On the
left is a logical statement, and on the right is the terms to include if
the statement is TRUE.

This resolves an issue where %S% has the terms on the right identical for
each group, which is rarely what happens in the data. In the pedestrian
example, the seasonality on weekends is simpler than weekdays. Using %?%
you can specify a simpler seasonal pattern (less K) on the weekend terms:
is_weekday(time) %?% fourier("day", K=9) + is_weekend(time) %?%
fourier("day", K=4)

**Comment by konradsemsch** [comment]
Really cool feature! I'm gonna test it out this week and will report back to you in case I came across any problems using it. There's probably a certain computational limit to the cardinality of such an event column I assume? So logical grouping of events might be helpful in such cases I guess.

**Comment by mitchelloharawild** [comment]
The main limit is the number of states you will create in the model. When you switch between states, this number can get large quickly. Using `%?%` over `%S%` allows you to reduce the number of states by creating states more specific to the structure you are capturing.

There is also potential for this to be faster by using sparse matrix algebra, as the switching states lead to sparsity - this would be done in #33.
